export default class Constant {
  // 登录标题大小
  static readonly LOGIN_SIZE: number = 30

  // 登录标题颜色
  static readonly LOGIN_COLOR: string = '#2F1155'

  // 输入框长度
  static readonly INPUT_WIDTH: number = 300

  // 输入框高度
  static readonly INPUT_HEIGHT: number = 60

  // 按钮宽度
  static readonly BUTTON_WIDTH: number = 150

  // 按钮高度
  static readonly BUTTON_HEIGHT: number = 50

  // 登录按钮颜色
  static readonly BUTTON_COLOR: string = '#6E34B8'
}